name: Pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - '*'
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      - name: Install node modules
        run: npm install
      - name: build prod
        run: npm run build
        if: always()
      - name: Eslint typescript
        run: npm run lint:ts
        if: always()
      - name: Scss
        run: npm run lint:scss
        if: always()
      - name: Unit testing
        run: npm run unit
        if: always()
      - name: Loki storybook screenshot
        run: npm run storybook:build && npm run loki:test --requireReference --reactUri file:./storybook-static
        if: always()
